using System;
using System.IO;
using System.Linq;
using System.Xml.Linq;
using System.Collections.Generic;
using FSMigrator;
class AutoTests {
 static int count;static void Check(bool value,string message){if(!value)throw new Exception(message);count++;Console.WriteLine("PASS "+message);}
 static void Throws(Action action,string message){try{action();}catch{Check(true,message);return;}throw new Exception("Expected rejection: "+message);}
 static int Main(){try{Run();return 0;}catch(Exception ex){Console.Error.WriteLine(ex);return 1;}} static void Run(){string root=Path.Combine(Path.GetTempPath(),"FlightBridge-auto-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);
  string steam=Path.Combine(root,"steam"),lib=Path.Combine(root,"library");Directory.CreateDirectory(Path.Combine(steam,"steamapps"));File.WriteAllText(Path.Combine(steam,"steamapps","libraryfolders.vdf"),"\"libraryfolders\" { \"0\" { \"path\" \""+lib.Replace("\\","\\\\")+"\" } }");Directory.CreateDirectory(Path.Combine(lib,"steamapps"));
  foreach(string id in new[]{"1250410","2537590"}){Directory.CreateDirectory(Path.Combine(lib,"steamapps","common",id));File.WriteAllText(Path.Combine(lib,"steamapps","appmanifest_"+id+".acf"),"\"installdir\" \""+id+"\"");string dir=Path.Combine(steam,"userdata","123",id,"remote");Directory.CreateDirectory(dir);File.Copy(id=="1250410"?"tests/fixtures/2020-fragment.xml":"tests/fixtures/2024-fragment.xml",Path.Combine(dir,"inputprofile_1"));File.WriteAllText(Path.Combine(Directory.GetParent(dir).FullName,"remotecache.vdf"),"\"inputprofile_1\" { }");File.WriteAllText(Path.Combine(dir,"logbook"),"preserve all non-profile data");}
  string targetRoot=Path.Combine(steam,"userdata","123","2537590");File.Copy(Path.Combine(targetRoot,"remote","inputprofile_1"),Path.Combine(targetRoot,"remote","inputprofile_2"));File.AppendAllText(Path.Combine(targetRoot,"remotecache.vdf"),"\"inputprofile_2\" { }");
  var stores=AutoMigration.Discover(steam,Path.Combine(root,"local"));Check(stores.Count==2&&stores.Sum(s=>s.Profiles.Count)==3&&stores.All(s=>s.InstallPath!=null),"Steam libraries and account discovered");
  var plan=AutoMigration.Build(stores);Check(plan.Ready&&plan.Changes.Count==2,"automatic device pairing");Check(XNode.DeepEquals(plan.Changes[0].Output.Root.Element("FriendlyName"),plan.Changes[0].Target.Xml.Root.Element("FriendlyName")),"target name and lock preserved");
  string target=plan.Changes[0].Target.Path,source=plan.Changes[0].Source.Path,original=Engine.Hash(target),sourceHash=Engine.Hash(source),backups=Path.Combine(root,"backups");
  string manifest=MigrationTransaction.Execute(plan,backups,()=>{},null);Check(Engine.Hash(target)!=original&&Engine.Hash(source)==sourceHash,"only target changed");var doc=MigrationTransaction.Verify(manifest);Check(doc.Root.Elements("Store").Count()==2&&doc.Descendants("File").Count()==7,"full backup includes cloud metadata and logbooks");Check(MigrationTransaction.HasEffectiveChanges(manifest),"effective backup session detected");Check(!MigrationTransaction.NeedsLegacyRepair(manifest),"current-version backup is not marked for repair");doc.Root.Attribute("AppVersion").Remove();doc.Save(manifest);Check(MigrationTransaction.NeedsLegacyRepair(manifest),"legacy transfer still applied is detected for automatic repair");var repeated=AutoMigration.Build(AutoMigration.Discover(steam,Path.Combine(root,"local")));Check(!repeated.Ready&&repeated.Changes.Count==0,"repeat transfer is detected as already current");MigrationTransaction.Restore(manifest,()=>{});Check(Engine.Hash(target)==original,"exact restore");MigrationTransaction.Restore(manifest,()=>{});Check(Engine.Hash(target)==original,"restore idempotent");
  plan=AutoMigration.Build(AutoMigration.Discover(steam,Path.Combine(root,"local")));Throws(()=>MigrationTransaction.Execute(plan,backups,()=>{},n=>{throw new IOException("injected");}),"write failure reported");Check(Engine.Hash(target)==original&&Engine.Hash(Path.Combine(targetRoot,"remote","inputprofile_2"))==original,"failure midway rolls back first target and leaves second intact");
  plan=AutoMigration.Build(AutoMigration.Discover(steam,Path.Combine(root,"local")));bool crash=false;Throws(()=>MigrationTransaction.Execute(plan,backups,()=>{if(crash)throw new IOException("process started");},n=>{crash=true;throw new IOException("interrupted");}),"interrupted rollback leaves journal");string pending=MigrationTransaction.Sessions(backups).Single(m=>MigrationTransaction.State(m)=="Pending");MigrationTransaction.Restore(pending,()=>{});Check(Engine.Hash(target)==original,"recovery after restart");
  plan=AutoMigration.Build(AutoMigration.Discover(steam,Path.Combine(root,"local")));manifest=MigrationTransaction.Execute(plan,backups,()=>{},null);File.AppendAllText(target,"<!-- user edit -->");string changed=Engine.Hash(target);Throws(()=>MigrationTransaction.Restore(manifest,()=>{}),"later user edits protected");Check(Engine.Hash(target)==changed,"conflict causes no overwrite");
  plan=AutoMigration.Build(AutoMigration.Discover(steam,Path.Combine(root,"local")));string staleRoot=Path.Combine(root,"stale");File.AppendAllText(source,"<!-- change -->");Throws(()=>MigrationTransaction.Execute(plan,staleRoot,()=>{},null),"changed source rejects stale plan before backup");Check(!Directory.Exists(staleRoot),"stale plan has no writes");
  plan=AutoMigration.Build(AutoMigration.Discover(steam,Path.Combine(root,"local")));File.WriteAllText(Path.Combine(targetRoot,"remotecache.vdf"),"unregistered");Throws(()=>MigrationTransaction.Execute(plan,Path.Combine(root,"unregistered"),()=>{},null),"unregistered target rejected");
  string copy=Path.Combine(Path.GetDirectoryName(manifest),"store-0","remote","logbook");File.AppendAllText(copy,"corruption");Throws(()=>MigrationTransaction.Verify(manifest),"non-profile backup corruption detected");
  File.Copy(source,source+".orig");Check(AutoMigration.Discover(steam,Path.Combine(root,"local"))[0].Profiles.Count==1,"orig excluded");
  var testStores=AutoMigration.Discover(steam,Path.Combine(root,"local"));var second=Profile.Read(source);second.Path=source+"duplicate";testStores[0].Profiles.Add(second);Check(!AutoMigration.Build(testStores).Ready,"ambiguous source not guessed");
  string wgsLocal=Path.Combine(root,"wgs-local");string wgs2020=Path.Combine(wgsLocal,"Packages","Microsoft.FlightSimulator_8wekyb3d8bbwe","SystemAppData","wgs");string wgs2024=Path.Combine(wgsLocal,"Packages","Microsoft.Limitless_8wekyb3d8bbwe","SystemAppData","wgs");
  foreach(string wgs in new[]{wgs2020,wgs2024}){string container=Path.Combine(wgs,"account","slot");Directory.CreateDirectory(container);File.WriteAllText(Path.Combine(wgs,"containers.index"),"registered");File.WriteAllText(Path.Combine(container,"container.1"),"metadata");}
  File.Copy("tests/fixtures/2020-fragment.xml",Path.Combine(wgs2020,"account","slot","source-blob"));File.Copy("tests/fixtures/2024-fragment.xml",Path.Combine(wgs2024,"account","slot","target-blob"));
  var wgsStores=AutoMigration.Discover(null,wgsLocal);var wgsPlan=AutoMigration.Build(wgsStores);Check(wgsPlan.Ready&&wgsPlan.Changes.Count==1,"existing WGS profile containers discovered");string wgsBefore=Engine.Hash(wgsPlan.Changes[0].Target.Path);string wgsManifest=MigrationTransaction.Execute(wgsPlan,Path.Combine(root,"wgs-backup"),()=>{},null);Check(Engine.Hash(wgsPlan.Changes[0].Target.Path)!=wgsBefore,"existing registered WGS blob updated");MigrationTransaction.Restore(wgsManifest,()=>{});Check(Engine.Hash(wgsPlan.Changes[0].Target.Path)==wgsBefore,"WGS blob restored byte for byte");
  doc=XDocument.Load(pending);doc.Root.Element("Change").SetAttributeValue("Path","..\\outside");doc.Save(pending);Throws(()=>MigrationTransaction.Verify(pending),"manifest traversal rejected");
  string empty=Path.Combine(root,"empty.xml");File.WriteAllText(empty,"<Version Num=\"1\"/><FriendlyName>Empty</FriendlyName><Device DeviceName=\"Test\" ProductID=\"1\"><Axes><Axis AxisName=\"X\"/></Axes></Device>");Check(Profile.Read(empty).Device.Elements("Context").Count()==0,"real axis-only profile parses without crashing");
  Console.WriteLine(count+" automatic migration checks passed; fixtures: "+root);
 }
}

